/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package createsession;

import Common.DBConnection;
import Subjects.subDettails;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Harendra Ranasinghe
 */
public class Sessions extends javax.swing.JFrame {

    /**
     * Creates new form Sessions
     */
    public Sessions() {
        initComponents();
        loaddata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("    SESSIONS DETAILS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 80));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Leturer Name", "Subject Name", "Tag", "GrpID", "StudentCount(Duration)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAlignmentY(1.5F);
        jTable2.setRowHeight(35);
        jScrollPane4.setViewportView(jTable2);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 940, 280));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("search");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 81, 36));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 180, 47));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, 195, 36));

        jButton4.setBackground(new java.awt.Color(0, 153, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 180, 47));

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 180, 47));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1000, 530));

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 180, 47));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new sessionmain().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    public String sub5;
    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:

        String id = jTextField2.getText();

        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            dtm.setRowCount(0);

            // ResultSet rs = DB.search("select * from sessions");
            ResultSet rs = DBConnection.search("select * from sessions where tag2 like '" + '%' + jTextField2.getText() + "%'OR subgrp1 like '" + "[" + '%' + jTextField2.getText() + "%'OR  grp2 like '" + "[" + jTextField2.getText() + "%' OR lec2 like '" + '%' + jTextField2.getText() + "%' OR sessionID like '" + jTextField2.getText() + "%'OR sub2 like '" + "[" + '%' + jTextField2.getText() + "%'");
            //      ResultSet rs = DB.search("select * from sessions where lec2 like '"+jTextField1.getText()+"%'");

            while (rs.next()) {
                String gette1 = rs.getString("lecturer");
                String gette2 = rs.getString("lec2");

                String sub = rs.getString("subject");
                String sube1 = rs.getString("sub2");

                String tag1 = rs.getString("tag");
                String tag2 = rs.getString("tag2");

                String grp1 = rs.getString("groupID");
                String grp2 = rs.getString("grp2");

                String subgrp1 = rs.getString("subGroupID");
                String subgrp2 = rs.getString("subgrp1");

                String count = rs.getString("studentCount");
                //  ResultSet rs27 = DB.search("select subjectName from subjects where empID like '"+gette1+"%'");

                String due = rs.getString("duration");

                String code = rs.getString("subjectCode");

                ResultSet rs26 = DBConnection.search("select lecturerName from lecturers where 	lecturerName like '" + id + "%'");

                while (rs26.next()) {

                    sub5 = rs26.getString("lecturerName");
                }

                Vector cc111 = new Vector();
                ResultSet rs55 = DBConnection.search("select lecturerName from lecturers where empID like '" + rs.getString("lecturer") + "'");

                while (rs55.next()) {

                    cc111.add(rs55.getString("lecturerName"));
                }

                Vector vv = new Vector();

                vv.add(rs.getString("sessionID"));
                vv.add(gette2);

                vv.add(sube1);
                vv.add(tag2);
                vv.add(grp1 + "," + grp2);
                vv.add(count + "(" + due + ")");

                dtm.addRow(vv);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jTextField2KeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        try {
            int i = jTable2.getSelectedRow();

            String id = (String) jTable2.getValueAt(i, 0);

            //  System.out.println(id);
            DBConnection.iud("delete from sessions  where sessionID='" + id + "'");

            JOptionPane.showMessageDialog(this, " Deleted....!", "Done", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new Sessions().setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid ", "Please Select row..!", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sessions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    private void loaddata() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            dtm.setRowCount(0);

            ResultSet rs = DBConnection.search("select * from sessions");

            while (rs.next()) {
                String gette1 = rs.getString("lecturer");
                String gette2 = rs.getString("lec2");

                String sub = rs.getString("subject");
                String sube1 = rs.getString("sub2");

                String tag1 = rs.getString("tag");
                String tag2 = rs.getString("tag2");

                String grp1 = rs.getString("groupID");
                String grp2 = rs.getString("grp2");

                String subgrp1 = rs.getString("subGroupID");
                String subgrp2 = rs.getString("subgrp1");

                String count = rs.getString("studentCount");
                //  ResultSet rs27 = DB.search("select subjectName from subjects where empID like '"+gette1+"%'");

                String due = rs.getString("duration");

                String code = rs.getString("subjectCode");

//           
//        
                Vector cc1 = new Vector();
                ResultSet rs55 = DBConnection.search("select lecturerName from lecturers where empID like '" + rs.getString("lecturer") + "'");

                while (rs55.next()) {

//                
                    cc1.add(rs55.getString("lecturerName"));
                }
//          

                Vector vv = new Vector();
                vv.add(rs.getString("sessionID"));
                vv.add(gette2);
                vv.add(sube1);
                vv.add(tag2);
                vv.add(grp1 + "," + grp2 + "," + subgrp1 + "," + subgrp2);
                vv.add(count + "(" + due + ")");

                dtm.addRow(vv);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
