/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WorkingDaysAndHours;

import Common.DBConnection;
import Common.IndexPage;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahmad Ahkam
 */
public class AddTimeSlots extends javax.swing.JFrame {

    Connection con = null;
    ButtonGroup bg;
    /**
     * Creates new form AddTimeSlots
     */
    public AddTimeSlots() {
        initComponents();
        
        bg = new ButtonGroup();
        bg.add(radioOneHour);
        bg.add(radiioMinutes);
        
        PreparedStatement stmt = null;
        ResultSet rs =  null;
        
        try{
            con = DBConnection.getDBConnection();

            String query = "SELECT batch FROM workingdaysandhours";
            stmt = con.prepareStatement(query);
            rs = stmt.executeQuery();
            
            ArrayList<String> batches = new ArrayList<String>();
            batches.add("Select");
            while(rs.next()){
                batches.add(rs.getString("batch"));
            }
            
            comboSelectBatch.setModel(new DefaultComboBoxModel<String>(batches.toArray(new String[0])));
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnHome = new javax.swing.JButton();
        btnAddWorkingDay = new javax.swing.JButton();
        btnAddTimeSlot = new javax.swing.JButton();
        btnViewDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboSelectBatch = new javax.swing.JComboBox<>();
        radioOneHour = new javax.swing.JRadioButton();
        radiioMinutes = new javax.swing.JRadioButton();
        comboHour = new javax.swing.JComboBox<>();
        comboMinutes = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEndTime = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Working Days And Hours");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 23, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 99, 1002, 10));

        btnHome.setBackground(new java.awt.Color(0, 153, 153));
        btnHome.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 180, 50));

        btnAddWorkingDay.setBackground(new java.awt.Color(0, 153, 153));
        btnAddWorkingDay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddWorkingDay.setText("Add Working Days");
        btnAddWorkingDay.setToolTipText("");
        btnAddWorkingDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWorkingDayActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddWorkingDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 180, 50));

        btnAddTimeSlot.setBackground(new java.awt.Color(0, 153, 153));
        btnAddTimeSlot.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnAddTimeSlot.setText("Add Time Slots");
        jPanel1.add(btnAddTimeSlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 180, 50));

        btnViewDelete.setBackground(new java.awt.Color(0, 153, 153));
        btnViewDelete.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnViewDelete.setText("View / Delete");
        btnViewDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 180, 50));

        btnEdit.setBackground(new java.awt.Color(0, 153, 153));
        btnEdit.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, 180, 50));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1002, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Add Time Slots");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Select Batch");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        comboSelectBatch.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        comboSelectBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSelectBatchActionPerformed(evt);
            }
        });
        jPanel1.add(comboSelectBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 200, -1));

        radioOneHour.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        radioOneHour.setText("One Hour");
        radioOneHour.setActionCommand("60");
        radioOneHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioOneHourActionPerformed(evt);
            }
        });
        jPanel1.add(radioOneHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        radiioMinutes.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        radiioMinutes.setText("Thirty Minutes");
        radiioMinutes.setActionCommand("30");
        radiioMinutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiioMinutesActionPerformed(evt);
            }
        });
        jPanel1.add(radiioMinutes, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, -1, -1));

        comboHour.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        comboHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21" }));
        comboHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboHourActionPerformed(evt);
            }
        });
        jPanel1.add(comboHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 70, -1));

        comboMinutes.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        comboMinutes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55" }));
        comboMinutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMinutesActionPerformed(evt);
            }
        });
        jPanel1.add(comboMinutes, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 70, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Start Time");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("End Time");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, -1));

        txtEndTime.setEditable(false);
        txtEndTime.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel1.add(txtEndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 180, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText(":");
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 16, -1));

        btnAdd.setBackground(new java.awt.Color(0, 153, 153));
        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 300, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Select Type");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnAddWorkingDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWorkingDayActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AddWorkingDaysAndHours().setVisible(true);
    }//GEN-LAST:event_btnAddWorkingDayActionPerformed

    private void btnViewDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDeleteActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ViewAndDelete().setVisible(true);
    }//GEN-LAST:event_btnViewDeleteActionPerformed

    private void comboSelectBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSelectBatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSelectBatchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:

        PreparedStatement stmt1, stmt2 = null;
        ResultSet rs = null;
        try {
            String type = bg.getSelection().getActionCommand();
            String startTimeHour = comboHour.getSelectedItem().toString();
            String startTimeMin = comboMinutes.getSelectedItem().toString();
            String batch = comboSelectBatch.getSelectedItem().toString();

            if(batch == "Select"){
                JOptionPane.showMessageDialog(this,"Please select a batch","Error",JOptionPane.ERROR_MESSAGE);
            }else if (startTimeHour == "--" || startTimeMin == "--") {
                JOptionPane.showMessageDialog(this,"Please select start time properly","Error",JOptionPane.ERROR_MESSAGE);
            }else {
                String startTime = startTimeHour+":"+startTimeMin+":00";
                String ty="";
                if(type=="30"){
                    ty="T";
                }else if(type=="60"){
                    ty="O";
                }

                String idRet = "SELECT workingID FROM workingdaysandhours WHERE batch=?";
                stmt1 = con.prepareStatement(idRet);
                stmt1.setString(1, batch);
                rs = stmt1.executeQuery();

                ArrayList<String> ids = new ArrayList<String>();
                while (rs.next()) {
                    ids.add(rs.getString(1));
                }
                
                String insertQuery = "INSERT INTO timeslots VALUES(?,?,?)";
                stmt2 = con.prepareStatement(insertQuery);
                stmt2.setString(1, startTime);
                stmt2.setString(2, ty);
                stmt2.setString(3, ids.get(0));
                stmt2.execute();
                
                JOptionPane.showMessageDialog(this, "Successfully Inserted.");
                
                this.setVisible(false);
                new AddTimeSlots().setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Duplicate Time Slots","Error",JOptionPane.ERROR_MESSAGE);
            
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void comboHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboHourActionPerformed
        // TODO add your handling code here:
        setEndTime();
    }//GEN-LAST:event_comboHourActionPerformed

    private void comboMinutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMinutesActionPerformed
        // TODO add your handling code here:
        setEndTime();
    }//GEN-LAST:event_comboMinutesActionPerformed

    private void radiioMinutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiioMinutesActionPerformed
        // TODO add your handling code here:
        setEndTime();
    }//GEN-LAST:event_radiioMinutesActionPerformed

    private void radioOneHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioOneHourActionPerformed
        // TODO add your handling code here:
        setEndTime();
    }//GEN-LAST:event_radioOneHourActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Edit().setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new IndexPage().setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    public void setEndTime(){
        String stH = comboHour.getSelectedItem().toString();
        String stM = comboMinutes.getSelectedItem().toString();
        String type = bg.getSelection().getActionCommand();
        
        if(!(stH == "--" || stM == "--")){
            int stHr = Integer.parseInt(stH);
            int stMs = Integer.parseInt(stM);
            
            if(type=="30"){
                stMs+=30;
                if(stMs>59){
                    stHr++;
                    stMs-=60;
                }
            }else if(type=="60"){
                stMs+=60;
                if(stMs>59){
                    stHr++;
                    stMs-=60;
                }
            }
            
            String minutes;
            if(stMs<10){
                minutes = "0"+stMs;
            }else{
                minutes = Integer.toString(stMs);
            }
            
            txtEndTime.setText(stHr + " : " + minutes);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTimeSlots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTimeSlots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTimeSlots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTimeSlots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTimeSlots().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddTimeSlot;
    private javax.swing.JButton btnAddWorkingDay;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnViewDelete;
    private javax.swing.JComboBox<String> comboHour;
    private javax.swing.JComboBox<String> comboMinutes;
    private javax.swing.JComboBox<String> comboSelectBatch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton radiioMinutes;
    private javax.swing.JRadioButton radioOneHour;
    private javax.swing.JTextField txtEndTime;
    // End of variables declaration//GEN-END:variables
}
