/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WorkingDaysAndHours;

import Common.DBConnection;
import Common.IndexPage;
import com.mysql.jdbc.Buffer;
import static java.awt.SystemColor.info;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahmad Ahkam
 */
public class AddWorkingDaysAndHours extends javax.swing.JFrame {

    /**
     * Creates new form AddWorkingDaysAndHours
     */
    public AddWorkingDaysAndHours() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboHours = new javax.swing.JComboBox<>();
        comboMinutes = new javax.swing.JComboBox<>();
        txtBatch = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnAddWorkingDay = new javax.swing.JButton();
        btnAddTimeSlot = new javax.swing.JButton();
        btnViewDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mondayCheckBox = new javax.swing.JCheckBox();
        tuesdayCheckBox = new javax.swing.JCheckBox();
        wednesdayCheckBox = new javax.swing.JCheckBox();
        thursdayCheckBox = new javax.swing.JCheckBox();
        fridayCheckBox = new javax.swing.JCheckBox();
        saturdayCheckBox = new javax.swing.JCheckBox();
        sundayCheckBox = new javax.swing.JCheckBox();
        comboDays = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Working Days and Hours");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        comboHours.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        comboHours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        jPanel1.add(comboHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, -1));

        comboMinutes.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        comboMinutes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "30" }));
        jPanel1.add(comboMinutes, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        txtBatch.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel1.add(txtBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 260, -1));

        btnAdd.setBackground(new java.awt.Color(0, 153, 153));
        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 220, 60));

        btnHome.setBackground(new java.awt.Color(0, 153, 153));
        btnHome.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnHome.setText("Home");
        btnHome.setToolTipText("");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 180, 50));

        btnAddWorkingDay.setBackground(new java.awt.Color(0, 153, 153));
        btnAddWorkingDay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddWorkingDay.setText("Add Working Days");
        jPanel1.add(btnAddWorkingDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 180, 50));

        btnAddTimeSlot.setBackground(new java.awt.Color(0, 153, 153));
        btnAddTimeSlot.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnAddTimeSlot.setText("Add Time Slots");
        btnAddTimeSlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTimeSlotActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddTimeSlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 180, 50));

        btnViewDelete.setBackground(new java.awt.Color(0, 153, 153));
        btnViewDelete.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnViewDelete.setText("View / Delete");
        btnViewDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 180, 50));

        btnEdit.setBackground(new java.awt.Color(0, 153, 153));
        btnEdit.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, 180, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Add Working Days");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Working Days per Week");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Working Days");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Working Time per Day");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Batch");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        mondayCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mondayCheckBox.setText("Monday");
        mondayCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mondayCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(mondayCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        tuesdayCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tuesdayCheckBox.setText("Tuesday");
        jPanel1.add(tuesdayCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        wednesdayCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wednesdayCheckBox.setText("Wednesday");
        jPanel1.add(wednesdayCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, -1));

        thursdayCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        thursdayCheckBox.setText("Thursday");
        thursdayCheckBox.setToolTipText("");
        jPanel1.add(thursdayCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, -1, -1));

        fridayCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fridayCheckBox.setText("Friday");
        jPanel1.add(fridayCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, -1, -1));

        saturdayCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saturdayCheckBox.setText("Saturday");
        saturdayCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saturdayCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(saturdayCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, -1, -1));

        sundayCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sundayCheckBox.setText("Sunday");
        sundayCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sundayCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(sundayCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 300, -1, -1));

        comboDays.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        comboDays.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        jPanel1.add(comboDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Hours");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Minutes");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("(Weekend, Weekdays, and etc)");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1000, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1000, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        Connection con = null;
        PreparedStatement stmt1,stmt2,stmt3 = null;
        ResultSet rs = null;
        
        try{
            ArrayList<String> selectedItems = new ArrayList<String>();
            
            if(mondayCheckBox.isSelected()){
                selectedItems.add(mondayCheckBox.getText().toString());
            }
            if(tuesdayCheckBox.isSelected()){
                selectedItems.add(tuesdayCheckBox.getText().toString());
            }
            if(wednesdayCheckBox.isSelected()){
                selectedItems.add(wednesdayCheckBox.getText().toString());
            }
            if(thursdayCheckBox.isSelected()){
                selectedItems.add(thursdayCheckBox.getText().toString());
            }
            if(fridayCheckBox.isSelected()){
                selectedItems.add(fridayCheckBox.getText().toString());
            }
            if(saturdayCheckBox.isSelected()){
                selectedItems.add(saturdayCheckBox.getText().toString());
            }
            if(sundayCheckBox.isSelected()){
                selectedItems.add(sundayCheckBox.getText().toString());
            }
            
            String id;
            int noOfWorkingDays = Integer.parseInt(comboDays.getSelectedItem().toString());
            int hours = Integer.parseInt(comboHours.getSelectedItem().toString());
            int minutes = Integer.parseInt(comboMinutes.getSelectedItem().toString());
            String batch = txtBatch.getText().toString();
            
            int duration = (hours*60)+minutes;
        
            con = DBConnection.getDBConnection();
            
            ////////////////////////////////////////////////////
            String retQuery = "SELECT workingID\n" +
                                "FROM workingdaysandhours\n" +
                                "WHERE workingID=(SELECT MAX(workingID)\n" +
                                "                FROM workingdaysandhours)";
            stmt2 = con.prepareStatement(retQuery);
            rs = stmt2.executeQuery();
            
            ArrayList workingIDs = new ArrayList();
            
            while (rs.next()) {
                workingIDs.add(rs.getString(1));
            }
            ////////////////////////////////////////////
            
            String lastID = "";
            int lastWID;
            if(workingIDs.size()==0){
                id="W0001";
            }else{
                lastID = workingIDs.get(0).toString();
                lastWID = Integer.parseInt(lastID.substring(1, 5));
                lastWID++;
                if(lastWID<10)
                    id = "W000"+lastWID;
                else if(lastWID<100)
                    id = "W00"+lastWID;
                else if(lastWID<1000)
                    id = "W0"+lastWID;
                else
                    id = "W"+lastWID;
            }
            ////////////////////////////////////////////
            
            if(selectedItems.size()!=noOfWorkingDays)
                JOptionPane.showMessageDialog(this,"Select Working Days according to No of Working Days per week","Error",JOptionPane.ERROR_MESSAGE);
            else if(duration == 0)
                JOptionPane.showMessageDialog(this,"Working Duration cannot be 0","Error",JOptionPane.ERROR_MESSAGE);
            else if(batch.equals(""))
                JOptionPane.showMessageDialog(this,"Batch cannot be null","Error",JOptionPane.ERROR_MESSAGE);
            else {
                String query = "insert into workingdaysandhours values(?,?,?,?)";
                stmt1 = con.prepareStatement(query);
                stmt1.setString(1, id);
                stmt1.setInt(2, duration);
                stmt1.setString(3, batch);
                stmt1.setInt(4, noOfWorkingDays);
                stmt1.execute();
                
                for (String day : selectedItems) {
                    stmt3 = null;
                    String query2 = "INSERT INTO days VALUES(?,?)";
                    stmt3 = con.prepareStatement(query2);
                    stmt3.setString(1, day);
                    stmt3.setString(2, id);
                    stmt3.execute();
                }
                
                JOptionPane.showMessageDialog(this, "Successfully Inserted.");
                
                this.dispose();
                new AddTimeSlots().setVisible(true);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Change batch name","Error",JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Edit().setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnViewDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDeleteActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ViewAndDelete().setVisible(true);
    }//GEN-LAST:event_btnViewDeleteActionPerformed

    private void mondayCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mondayCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mondayCheckBoxActionPerformed

    private void saturdayCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saturdayCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saturdayCheckBoxActionPerformed

    private void sundayCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sundayCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sundayCheckBoxActionPerformed

    private void btnAddTimeSlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTimeSlotActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AddTimeSlots().setVisible(true);
    }//GEN-LAST:event_btnAddTimeSlotActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new IndexPage().setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddWorkingDaysAndHours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddWorkingDaysAndHours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddWorkingDaysAndHours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddWorkingDaysAndHours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddWorkingDaysAndHours().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddTimeSlot;
    private javax.swing.JButton btnAddWorkingDay;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnViewDelete;
    private javax.swing.JComboBox<String> comboDays;
    private javax.swing.JComboBox<String> comboHours;
    private javax.swing.JComboBox<String> comboMinutes;
    private javax.swing.JCheckBox fridayCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JCheckBox mondayCheckBox;
    private javax.swing.JCheckBox saturdayCheckBox;
    private javax.swing.JCheckBox sundayCheckBox;
    private javax.swing.JCheckBox thursdayCheckBox;
    private javax.swing.JCheckBox tuesdayCheckBox;
    private javax.swing.JTextField txtBatch;
    private javax.swing.JCheckBox wednesdayCheckBox;
    // End of variables declaration//GEN-END:variables
}
