/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WorkingDaysAndHours;

import Common.DBConnection;
import Common.IndexPage;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahmad Ahkam
 */
public class Edit extends javax.swing.JFrame {

    Connection con = null;
    /**
     * Creates new form Edit
     */
    public Edit() {
        initComponents();
        
        PreparedStatement stmt = null;
        ResultSet rs =  null;
        
        try{
            con = DBConnection.getDBConnection();

            String query = "SELECT batch FROM workingdaysandhours";
            stmt = con.prepareStatement(query);
            rs = stmt.executeQuery();
            
            ArrayList<String> batches = new ArrayList<String>();
            batches.add("Select");
            while(rs.next()){
                batches.add(rs.getString("batch"));
            }
            
            comboSelectBatch.setModel(new DefaultComboBoxModel<String>(batches.toArray(new String[0])));
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnHome = new javax.swing.JButton();
        btnAddWorkingDay = new javax.swing.JButton();
        btnAddTimeSlot = new javax.swing.JButton();
        btnViewDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        comboSelectBatch = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comboDays = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboHour = new javax.swing.JComboBox<>();
        mondayCheckBox = new javax.swing.JCheckBox();
        tuesdayCheckBox = new javax.swing.JCheckBox();
        wednesdayCheckBox = new javax.swing.JCheckBox();
        thursdayCheckBox = new javax.swing.JCheckBox();
        fridayCheckBox = new javax.swing.JCheckBox();
        saturdayCheckBox = new javax.swing.JCheckBox();
        sundayCheckBox = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        comboMinutes = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtBatch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Working Days and Hours");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 600, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1000, 10));

        btnHome.setBackground(new java.awt.Color(0, 153, 153));
        btnHome.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 180, 50));

        btnAddWorkingDay.setBackground(new java.awt.Color(0, 153, 153));
        btnAddWorkingDay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddWorkingDay.setText("Add Working Days");
        btnAddWorkingDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWorkingDayActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddWorkingDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 180, 50));

        btnAddTimeSlot.setBackground(new java.awt.Color(0, 153, 153));
        btnAddTimeSlot.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnAddTimeSlot.setText("Add Time Slots");
        btnAddTimeSlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTimeSlotActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddTimeSlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 180, 50));

        btnViewDelete.setBackground(new java.awt.Color(0, 153, 153));
        btnViewDelete.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnViewDelete.setText("View / Delete");
        btnViewDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 180, 50));

        btnEdit.setBackground(new java.awt.Color(0, 153, 153));
        btnEdit.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnEdit.setText("Edit");
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, 180, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Edit Working Days and Hours");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1000, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Select Batch");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        comboSelectBatch.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        comboSelectBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSelectBatchActionPerformed(evt);
            }
        });
        jPanel1.add(comboSelectBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 200, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Working Days per Week");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        comboDays.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        comboDays.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        jPanel1.add(comboDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Working Days");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Working Time per Day");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, 31));

        comboHour.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        comboHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        jPanel1.add(comboHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 80, -1));

        mondayCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mondayCheckBox.setText("Monday");
        mondayCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mondayCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(mondayCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        tuesdayCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tuesdayCheckBox.setText("Tuesday");
        jPanel1.add(tuesdayCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, -1));

        wednesdayCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wednesdayCheckBox.setText("Wednesday");
        jPanel1.add(wednesdayCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, -1));

        thursdayCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        thursdayCheckBox.setText("Thursday");
        thursdayCheckBox.setToolTipText("");
        jPanel1.add(thursdayCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, -1, -1));

        fridayCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fridayCheckBox.setText("Friday");
        jPanel1.add(fridayCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, -1, -1));

        saturdayCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saturdayCheckBox.setText("Saturday");
        saturdayCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saturdayCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(saturdayCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, -1, -1));

        sundayCheckBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sundayCheckBox.setText("Sunday");
        sundayCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sundayCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(sundayCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 350, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Hours");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, -1, -1));

        comboMinutes.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        comboMinutes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "30" }));
        jPanel1.add(comboMinutes, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 80, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("Minutes");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, -1, -1));

        txtBatch.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel1.add(txtBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 230, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Batch");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(0, 153, 153));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, 180, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String selectedID;
    
    private void btnAddWorkingDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWorkingDayActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AddWorkingDaysAndHours().setVisible(true);
    }//GEN-LAST:event_btnAddWorkingDayActionPerformed

    private void btnAddTimeSlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTimeSlotActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AddTimeSlots().setVisible(true);
    }//GEN-LAST:event_btnAddTimeSlotActionPerformed

    private void btnViewDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDeleteActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ViewAndDelete().setVisible(true);
    }//GEN-LAST:event_btnViewDeleteActionPerformed

    private void mondayCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mondayCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mondayCheckBoxActionPerformed

    private void saturdayCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saturdayCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saturdayCheckBoxActionPerformed

    private void sundayCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sundayCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sundayCheckBoxActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        PreparedStatement stmt1,stmt2,stmt3 = null;
        ResultSet rs = null;
        
        try{
            ArrayList<String> selectedItems = new ArrayList<String>();
            
            if(mondayCheckBox.isSelected()){
                selectedItems.add(mondayCheckBox.getText().toString());
            }
            if(tuesdayCheckBox.isSelected()){
                selectedItems.add(tuesdayCheckBox.getText().toString());
            }
            if(wednesdayCheckBox.isSelected()){
                selectedItems.add(wednesdayCheckBox.getText().toString());
            }
            if(thursdayCheckBox.isSelected()){
                selectedItems.add(thursdayCheckBox.getText().toString());
            }
            if(fridayCheckBox.isSelected()){
                selectedItems.add(fridayCheckBox.getText().toString());
            }
            if(saturdayCheckBox.isSelected()){
                selectedItems.add(saturdayCheckBox.getText().toString());
            }
            if(sundayCheckBox.isSelected()){
                selectedItems.add(sundayCheckBox.getText().toString());
            }
            
            int noOfWorkingDays = Integer.parseInt(comboDays.getSelectedItem().toString());
            int hours = Integer.parseInt(comboHour.getSelectedItem().toString());
            int minutes = Integer.parseInt(comboMinutes.getSelectedItem().toString());
            String batch = txtBatch.getText().toString();
            
            int duration = (hours*60)+minutes;
        
            con = DBConnection.getDBConnection();
            
            ////////////////////////////////////////////
            
            if(selectedItems.size()!=noOfWorkingDays)
                JOptionPane.showMessageDialog(this,"Select Working Days according to No of Working Days per week","Error",JOptionPane.ERROR_MESSAGE);
            else if(duration == 0)
                JOptionPane.showMessageDialog(this,"Working Duration cannot be 0","Error",JOptionPane.ERROR_MESSAGE);
            else if(batch.equals(""))
                JOptionPane.showMessageDialog(this,"Batch cannot be null","Error",JOptionPane.ERROR_MESSAGE);
            else {
                String query = "UPDATE workingdaysandhours SET workingDuration=?, batch=?, noOfWorkingDays=? WHERE workingID=?";
                stmt1 = con.prepareStatement(query);
                stmt1.setInt(1, duration);
                stmt1.setString(2, batch);
                stmt1.setInt(3, noOfWorkingDays);
                stmt1.setString(4, selectedID);
                stmt1.execute();
                
                String query1 = "DELETE FROM days WHERE workingID=?";
                stmt2 = con.prepareStatement(query1);
                stmt2.setString(1, selectedID);
                stmt2.execute();
                
                for (String day : selectedItems) {
                    stmt3 = null;
                    String query2 = "INSERT INTO days VALUES(?,?)";
                    stmt3 = con.prepareStatement(query2);
                    stmt3.setString(1, day);
                    stmt3.setString(2, selectedID);
                    stmt3.execute();
                }
                
                JOptionPane.showMessageDialog(this, "Successfully Updated.");
                System.out.println("Successfully Updated");
                
                this.dispose();
                new Edit().setVisible(true);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Cannot Insert","Error",JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void comboSelectBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSelectBatchActionPerformed
        // TODO add your handling code here:
        PreparedStatement stmt,stmt2,stmt3 = null;
        ResultSet rs,rs2,rs3 = null;
        
        try{
            mondayCheckBox.setSelected(false);
            tuesdayCheckBox.setSelected(false);
            wednesdayCheckBox.setSelected(false);
            thursdayCheckBox.setSelected(false);
            saturdayCheckBox.setSelected(false);
            fridayCheckBox.setSelected(false);
            sundayCheckBox.setSelected(false);
            
            String batch = comboSelectBatch.getSelectedItem().toString();
            
            String query = "SELECT workingID FROM workingDaysAndHours WHERE batch=?";
            stmt = con.prepareStatement(query);
            stmt.setString(1, batch);
            rs = stmt.executeQuery();
            
            ArrayList<String> ID = new ArrayList<String>();
            while(rs.next()){
                ID.add(rs.getString(1));
            }
            selectedID = ID.get(0);
            
            String query1 = "SELECT noOfWorkingDays, workingDuration, batch FROM workingdaysandhours WHERE workingID=?";
            stmt2 = con.prepareStatement(query1);
            stmt2.setString(1, selectedID);
            rs2 = stmt2.executeQuery();
            
            ArrayList<String> table1Data = new ArrayList<String>();
            while(rs2.next()){
                table1Data.add(rs2.getString(1));
                table1Data.add(rs2.getString(2));
                table1Data.add(rs2.getString(3));
            }
            
            String query2 = "SELECT day FROM days WHERE workingID=?";
            stmt3 = con.prepareStatement(query2);
            stmt3.setString(1, selectedID);
            rs3 = stmt3.executeQuery();
            
            ArrayList<String> table2Data = new ArrayList<String>();
            while(rs3.next()){
                table2Data.add(rs3.getString(1));
            }
            
            comboDays.setSelectedItem(table1Data.get(0));
            int duration = Integer.parseInt(table1Data.get(1));
            comboHour.setSelectedItem(Integer.toString(duration/60));
            if(duration%60 == 0){
                comboMinutes.setSelectedItem("00");
            }else{
                comboMinutes.setSelectedItem("30");
            }
            txtBatch.setText(table1Data.get(2));
            
            
            for(String day:table2Data){
                if(day.equals("Monday"))
                    mondayCheckBox.setSelected(true);
                else if(day.equals("Tuesday"))
                    tuesdayCheckBox.setSelected(true);
                else if(day.equals("Wednesday"))
                    wednesdayCheckBox.setSelected(true);
                else if(day.equals("Thursday"))
                    thursdayCheckBox.setSelected(true);
                else if(day.equals("Friday"))
                    fridayCheckBox.setSelected(true);
                else if(day.equals("Saturday"))
                    saturdayCheckBox.setSelected(true);
                else if(day.equals("Sunday"))
                    sundayCheckBox.setSelected(true);
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_comboSelectBatchActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new IndexPage().setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTimeSlot;
    private javax.swing.JButton btnAddWorkingDay;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewDelete;
    private javax.swing.JComboBox<String> comboDays;
    private javax.swing.JComboBox<String> comboHour;
    private javax.swing.JComboBox<String> comboMinutes;
    private javax.swing.JComboBox<String> comboSelectBatch;
    private javax.swing.JCheckBox fridayCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JCheckBox mondayCheckBox;
    private javax.swing.JCheckBox saturdayCheckBox;
    private javax.swing.JCheckBox sundayCheckBox;
    private javax.swing.JCheckBox thursdayCheckBox;
    private javax.swing.JCheckBox tuesdayCheckBox;
    private javax.swing.JTextField txtBatch;
    private javax.swing.JCheckBox wednesdayCheckBox;
    // End of variables declaration//GEN-END:variables
}
