/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WorkingDaysAndHours;

import Common.DBConnection;
import Common.IndexPage;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ahmad Ahkam
 */
public class ViewAndDelete extends javax.swing.JFrame {

    Connection con = null;
    
    /**
     * Creates new form ViewAndDelete
     */
    public ViewAndDelete() {
        initComponents();
        
        PreparedStatement stmt = null;
        ResultSet rs =  null;
        
        try{
            con = DBConnection.getDBConnection();

            String query = "SELECT batch FROM workingdaysandhours";
            stmt = con.prepareStatement(query);
            rs = stmt.executeQuery();
            
            ArrayList<String> batches = new ArrayList<String>();
            
            while(rs.next()){
                batches.add(rs.getString("batch"));
            }
            
            comboSelectBatch.setModel(new DefaultComboBoxModel<String>(batches.toArray(new String[0])));
            
            displayContent(batches.get(0));
            loadData();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnAddWorkingDay = new javax.swing.JButton();
        btnAddTimeSlot = new javax.swing.JButton();
        btnViewDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboSelectBatch = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        printNoOfWorkingDays = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        printDays = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        printNoOfHours = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboSelectTimeSlot = new javax.swing.JComboBox<>();
        btnDeleteTimeSlot = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Working Days and Hours");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        btnHome.setBackground(new java.awt.Color(0, 153, 153));
        btnHome.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 681, 107));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("View and Delete");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        btnAddWorkingDay.setBackground(new java.awt.Color(0, 153, 153));
        btnAddWorkingDay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddWorkingDay.setText("Add Working Days");
        btnAddWorkingDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWorkingDayActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddWorkingDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 180, 50));

        btnAddTimeSlot.setBackground(new java.awt.Color(0, 153, 153));
        btnAddTimeSlot.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnAddTimeSlot.setText("Add Time Slots");
        btnAddTimeSlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTimeSlotActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddTimeSlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 180, 50));

        btnViewDelete.setBackground(new java.awt.Color(0, 153, 153));
        btnViewDelete.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnViewDelete.setText("View / Delete");
        jPanel1.add(btnViewDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 180, 50));

        btnEdit.setBackground(new java.awt.Color(0, 153, 153));
        btnEdit.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 180, 50));

        btnDelete.setBackground(new java.awt.Color(0, 153, 153));
        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 180, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Select batch");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        comboSelectBatch.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        comboSelectBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSelectBatchActionPerformed(evt);
            }
        });
        jPanel1.add(comboSelectBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 200, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1000, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1000, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Working Days per Week :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        printNoOfWorkingDays.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        printNoOfWorkingDays.setText("jLabel7");
        jPanel1.add(printNoOfWorkingDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Working Days :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        printDays.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        printDays.setText("jLabel8");
        jPanel1.add(printDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Working Time per Day :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));

        printNoOfHours.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        printNoOfHours.setText("jLabel9");
        jPanel1.add(printNoOfHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Time Slots");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, -1, -1));

        comboSelectTimeSlot.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel1.add(comboSelectTimeSlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, 256, 39));

        btnDeleteTimeSlot.setBackground(new java.awt.Color(0, 153, 153));
        btnDeleteTimeSlot.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnDeleteTimeSlot.setText("Delete");
        btnDeleteTimeSlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTimeSlotActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeleteTimeSlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 540, 256, 41));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 1000, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String selectedID;
    
    private void loadData() {
        PreparedStatement stmt = null;
        ResultSet rs = null;
        
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setColumnIdentifiers(new String [] {"Start Time","Type"});
            dtm.setRowCount(0);

            String query = "SELECT startTime, type FROM timeslots WHERE workingID=?";
            stmt = con.prepareStatement(query);
            stmt.setString(1, selectedID);
            rs = stmt.executeQuery();

            while (rs.next()) {
                Vector vector = new Vector();

                String time = rs.getString(1);
                String ty = rs.getString(2);

                vector.add(time);
                
                if(ty.equals("T")){
                    vector.add("Thirty Minutes");
                }else {
                    vector.add("One Hour");
                }
                dtm.addRow(vector);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    
    public void displayContent(String batch){
        PreparedStatement stmt,stmt1,stmt2 = null;
        ResultSet rs,rs1,rs2 = null;
        
        try{
            String retriveQuery = "SELECT workingID,workingDuration,noOfWorkingDays FROM workingdaysandhours WHERE batch=?";
            stmt = con.prepareStatement(retriveQuery);
            stmt.setString(1, batch);
            rs = stmt.executeQuery();
            
            ArrayList<String> list = new ArrayList<String>();
            while(rs.next()){
                list.add(rs.getString(1));
                list.add(rs.getString(2));
                list.add(rs.getString(3));
            }
            
            //Working time convert to hours and minutes
            int duration = Integer.parseInt(list.get(1));
            String workingTime = (duration/60)+" Hours and "+ (duration%60)+" Minutes";
            
            printNoOfWorkingDays.setText(list.get(2));
            printNoOfHours.setText(workingTime);
            
            String retriveQuery1 = "SELECT day FROM days WHERE workingID=?";
            stmt1 = con.prepareStatement(retriveQuery1);
            stmt1.setString(1, list.get(0));
            rs1 = stmt1.executeQuery();
            
            selectedID = list.get(0);
            
            ArrayList<String> days = new ArrayList<String>();
            while(rs1.next()){
                days.add(rs1.getString(1));
            }
            
            StringBuilder dayArr = new StringBuilder();
            for(String day:days){
                dayArr.append(day+", ");
            }
            
            dayArr.deleteCharAt(dayArr.length() -2);
            printDays.setText(dayArr.toString());
            
            String retriveQuery2 = "SELECT startTime FROM timeslots WHERE workingID=?";
            stmt2 = con.prepareStatement(retriveQuery2);
            stmt2.setString(1, selectedID);
            rs2 = stmt2.executeQuery();
            
            ArrayList<String> timeslots = new ArrayList<String>();
            
            while(rs2.next()){
                timeslots.add(rs2.getString(1));
            }
            
            comboSelectTimeSlot.setModel(new DefaultComboBoxModel<String>(timeslots.toArray(new String[0])));
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public void printTable(){
        PreparedStatement stmt = null;
        ResultSet rs = null;
        
        try{
            String query = "SELECT startTime, type FROM timeslots WHERE workingID=?";
            stmt = con.prepareStatement(query);
            stmt.setString(1, selectedID);
            rs = stmt.executeQuery();
            
            int count = 0;
            ArrayList<String> timeslots = new ArrayList<String>();
            while(rs.next()){
                timeslots.add(rs.getString(1));
                if(rs.getString(2) == "O"){
                    timeslots.add("One Hour");
                }else{
                    timeslots.add("Thirty Minutes");
                }
                count++;
            }
            
            
            
        }catch (Exception e){
            e.printStackTrace();
        }
    }
    
    private void btnAddWorkingDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWorkingDayActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AddWorkingDaysAndHours().setVisible(true);
    }//GEN-LAST:event_btnAddWorkingDayActionPerformed

    private void btnAddTimeSlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTimeSlotActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AddTimeSlots().setVisible(true);
    }//GEN-LAST:event_btnAddTimeSlotActionPerformed

    private void comboSelectBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSelectBatchActionPerformed
        // TODO add your handling code here:
        displayContent(comboSelectBatch.getSelectedItem().toString());
        loadData();
    }//GEN-LAST:event_comboSelectBatchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Confirm to delete","Warning",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            PreparedStatement stmt = null;
        try {
            String query = "DELETE FROM workingdaysandhours WHERE workingID=?";
            stmt = con.prepareStatement(query);
            stmt.setString(1, selectedID);
            stmt.execute();
            
            JOptionPane.showMessageDialog(this, "Successfully Deleted.");
            
            this.dispose();
            new ViewAndDelete().setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Edit().setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteTimeSlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTimeSlotActionPerformed
        // TODO add your handling code here:
        
        if(JOptionPane.showConfirmDialog(null, "Confirm to delete","Warning",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
        PreparedStatement stmt = null;
        try {
            String startTime = comboSelectTimeSlot.getSelectedItem().toString();
            
            String query = "DELETE FROM timeslots WHERE startTime=?";
            stmt = con.prepareStatement(query);
            stmt.setString(1, startTime);
            stmt.execute();
            
            JOptionPane.showMessageDialog(this, "Successfully Deleted.");
            
            this.dispose();
            new ViewAndDelete().setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_btnDeleteTimeSlotActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new IndexPage().setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAndDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAndDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAndDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAndDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAndDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTimeSlot;
    private javax.swing.JButton btnAddWorkingDay;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteTimeSlot;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnViewDelete;
    private javax.swing.JComboBox<String> comboSelectBatch;
    private javax.swing.JComboBox<String> comboSelectTimeSlot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel printDays;
    private javax.swing.JLabel printNoOfHours;
    private javax.swing.JLabel printNoOfWorkingDays;
    // End of variables declaration//GEN-END:variables
}
