/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Subjects;

import Common.DBConnection;
import Lecturers.Lec_Details;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ranasinghe
 */
public class subDettails extends javax.swing.JFrame {

    /**
     * Creates new form subDettails
     */
    public subDettails() {
         subDettails.this.setTitle("Subjects Details");
        initComponents();
        loaddata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton1.setText("HOME");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 180, 47));

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 180, 47));

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton3.setText("Remove Subject");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 180, 47));

        jButton4.setBackground(new java.awt.Color(0, 153, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton4.setText("Edit Subject");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 180, 47));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Search");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 100, 30));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 190, 30));

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sub_Code", "SUb_Name", "Year", "Semester", "Lec_Hrs", "Tut_Hrs", "Lab_Hrs", "Eve_Hrs"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 860, 210));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1000, 510));

        jPanel4.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText(" SUBJECTS DETAILS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(318, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(292, 292, 292))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 90));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

new MainSubject().setVisible(true);
        this.setVisible(false);        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        
        
         try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);

            ResultSet rs = DBConnection.search("select * from subjects where subjectName like '"+jTextField1.getText()+"%'");
            // ResultSet rs1 = DB.search("select * from lecturers where lecturerName like '"+jTextField1.getText()+"%'");

            while (rs.next()) {
                Vector vv = new Vector();

                //                vv.add(rs.getString("yearAndSemester"));
               
                 String gette = rs.getString("subjectCode");
                String gette2 = rs.getString("subjectName");
                String gette3 = rs.getString("offeredYear");
                String gette4 = rs.getString("offeredSemester");
                String gette5 = rs.getString("noOfLecHours");
                String gette6 = rs.getString("noOfTuteHours");
                String gette7 = rs.getString("noOfLabHours");
                String gette8 = rs.getString("noOfEvalutionHours");
                //String gette1 = rs1.getString("lecturerName");

                vv.add(gette3);
                 vv.add(gette4);
                  vv.add(gette2);
                  vv.add(gette);
                 vv.add(gette5);
                  vv.add(gette6);
                  vv.add(gette7);
                  vv.add(gette8);
                dtm.addRow(vv);

                //                 vv.add(gette1);
                //                dtm.addRow(vv);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
          try {
            int i = jTable1.getSelectedRow();
            String subjectCode = (String) jTable1.getValueAt(i, 0);
             String subjectName = (String) jTable1.getValueAt(i, 1);
              String offeredYear = (String) jTable1.getValueAt(i, 2);
               String offeredSemester = (String) jTable1.getValueAt(i, 3);
                String noOfLecHours = (String) jTable1.getValueAt(i, 4);
                 String noOfTuteHours = (String) jTable1.getValueAt(i, 5);
                  String noOfLabHours = (String) jTable1.getValueAt(i, 6);
                   String noOfEvalutionHours = (String) jTable1.getValueAt(i, 7);
                  // String rank = (String) jTable1.getValueAt(i, 7);
              //   subjectCode,subjectName,offeredYear,offeredSemester,noOfLecHours,noOfTuteHours,noOfLabHours,noOfEvalutionHours
              
           // System.out.println(yrs);
            
           DBConnection.iud("update  subjects SET subjectName='" + subjectName + "',offeredYear='" + offeredYear + "',offeredSemester='" + offeredSemester + "',noOfLecHours='" + noOfLecHours + "',noOfTuteHours='" + noOfTuteHours + "',noOfLabHours='" + noOfLabHours + "',noOfEvalutionHours='" + noOfEvalutionHours + "' where subjectCode='" + subjectCode+ "'");
                
                JOptionPane.showMessageDialog(this, " Updated....!", "Done", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new subDettails().setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Details", "Please Enter Valid Records To Update Data..!", JOptionPane.ERROR_MESSAGE);
				
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Confirm to delete","Warning",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
        
         try {
            int i = jTable1.getSelectedRow();
           
                 String id = (String) jTable1.getValueAt(i, 0);
              
           // System.out.println(yrs);
            
            DBConnection.iud("delete from subjects  where subjectCode='" + id+ "'");
                
                JOptionPane.showMessageDialog(this, " Deleted....!", "Done", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new subDettails().setVisible(true);

        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "Invalid ", "Please Select row..!", JOptionPane.ERROR_MESSAGE);
				
        }
        }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(subDettails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(subDettails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(subDettails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(subDettails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new subDettails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

private void loaddata() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);

            ResultSet rs = DBConnection.search("select * from subjects");

            while (rs.next()) {
                Vector vv = new Vector();

            //    vv.add(rs.getString("yearAndSemester"));
            //    subjectCode,subjectName,offeredYear,offeredSemester,noOfLecHours,noOfTuteHours,noOfLabHours,noOfEvalutionHours
                String gette = rs.getString("subjectCode");
                String gette2 = rs.getString("subjectName");
                String gette3 = rs.getString("offeredYear");
                String gette4 = rs.getString("offeredSemester");
                String gette5 = rs.getString("noOfLecHours");
                String gette6 = rs.getString("noOfTuteHours");
                String gette7 = rs.getString("noOfLabHours");
                String gette8 = rs.getString("noOfEvalutionHours");
                

//                String ar[] = gette.split("");
//                vv.add(ar[0] + ar[1]);
//                vv.add(ar[3] + ar[4]);
                vv.add(gette);
                 vv.add(gette2);
                  vv.add(gette3);
                  vv.add(gette4);
                 vv.add(gette5);
                  vv.add(gette6);
                  vv.add(gette7);
                  vv.add(gette8);

                dtm.addRow(vv);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }


}
